### PR TITLE
Add Github Action CI job and fix the build for Linux ARM64

### PR DESCRIPTION
**Pull request by martin-g**
Related to https://github.com/sortmerna/sortmerna/issues/415

### CODE REVIEW

**Comment by martin-g** [comment]
The Linux ARM64 CI job will fail with the following error:
```
package_config_destination: /tmp/sortmerna/sortmerna/dist/cmake/sortmerna
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/sortmerna/sortmerna/build/release
[proc_run] Run time: 0.6937391757965088
[proc_run] Running in /tmp/sortmerna/sortmerna:
===========================================================
cmake --build --preset LIN_release --target install
===========================================================
[14/75] Building C object 3rdparty/cmph/CMakeFiles/cmph.dir/Release/brz.c.o
/tmp/sortmerna/sortmerna/3rdparty/cmph/brz.c: In function ‘brz_pack’:
/tmp/sortmerna/sortmerna/3rdparty/cmph/brz.c:804:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  804 |    *g_is_ptr++ = (cmph_uint32)g_i;
      |                  ^
/tmp/sortmerna/sortmerna/3rdparty/cmph/brz.c: In function ‘brz_bmz8_search_packed’:
/tmp/sortmerna/sortmerna/3rdparty/cmph/brz.c:912:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  912 |  register cmph_uint8 * h1_ptr = (cmph_uint8 *) g_is_ptr[h0];
      |                                 ^
/tmp/sortmerna/sortmerna/3rdparty/cmph/brz.c: In function ‘brz_fch_search_packed’:
/tmp/sortmerna/sortmerna/3rdparty/cmph/brz.c:968:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  968 |  register cmph_uint8 * h1_ptr = (cmph_uint8 *) g_is_ptr[h0];
      |                                 ^
[33/75] Building CXX object src/sortmerna/CMakeFiles/smr_objs.dir/Release/alignment.cpp.o
FAILED: src/sortmerna/CMakeFiles/smr_objs.dir/Release/alignment.cpp.o 
/usr/bin/c++ -DCMAKE_INTDIR=\"Release\" -I/tmp/sortmerna/sortmerna/include -I/tmp/sortmerna/sortmerna/3rdparty/cmph -I/tmp/sortmerna/sortmerna/3rdparty/concurrentqueue -I/tmp/sortmerna/sortmerna/3rdparty/alp -isystem /tmp/sortmerna/sortmerna/build/3rdparty/rocksdb/dist/include -isystem /tmp/sortmerna/sortmerna/build/3rdparty/zlib/dist/include -W -Wextra -Wall -Xlinker -v -O3 -DNDEBUG -std=gnu++17 -MD -MT src/sortmerna/CMakeFiles/smr_objs.dir/Release/alignment.cpp.o -MF src/sortmerna/CMakeFiles/smr_objs.dir/Release/alignment.cpp.o.d -o src/sortmerna/CMakeFiles/smr_objs.dir/Release/alignment.cpp.o -c /tmp/sortmerna/sortmerna/src/sortmerna/alignment.cpp
In file included from /tmp/sortmerna/sortmerna/include/indexdb.hpp:40,
                 from /tmp/sortmerna/sortmerna/include/bitvector.hpp:42,
                 from /tmp/sortmerna/sortmerna/include/traverse_bursttrie.hpp:46,
                 from /tmp/sortmerna/sortmerna/include/alignment.hpp:42,
                 from /tmp/sortmerna/sortmerna/src/sortmerna/alignment.cpp:39:
/tmp/sortmerna/sortmerna/include/ssw.h:25:10: fatal error: emmintrin.h: No such file or directory
   25 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
[34/75] Building CXX object src/sortmerna/CMakeFiles/smr_objs.dir/Release/bitvector.cpp.o
FAILED: src/sortmerna/CMakeFiles/smr_objs.dir/Release/bitvector.cpp.o 
/usr/bin/c++ -DCMAKE_INTDIR=\"Release\" -I/tmp/sortmerna/sortmerna/include -I/tmp/sortmerna/sortmerna/3rdparty/cmph -I/tmp/sortmerna/sortmerna/3rdparty/concurrentqueue -I/tmp/sortmerna/sortmerna/3rdparty/alp -isystem /tmp/sortmerna/sortmerna/build/3rdparty/rocksdb/dist/include -isystem /tmp/sortmerna/sortmerna/build/3rdparty/zlib/dist/include -W -Wextra -Wall -Xlinker -v -O3 -DNDEBUG -std=gnu++17 -MD -MT src/sortmerna/CMakeFiles/smr_objs.dir/Release/bitvector.cpp.o -MF src/sortmerna/CMakeFiles/smr_objs.dir/Release/bitvector.cpp.o.d -o src/sortmerna/CMakeFiles/smr_objs.dir/Release/bitvector.cpp.o -c /tmp/sortmerna/sortmerna/src/sortmerna/bitvector.cpp
In file included from /tmp/sortmerna/sortmerna/include/indexdb.hpp:40,
                 from /tmp/sortmerna/sortmerna/include/bitvector.hpp:42,
                 from /tmp/sortmerna/sortmerna/src/sortmerna/bitvector.cpp:39:
/tmp/sortmerna/sortmerna/include/ssw.h:25:10: fatal error: emmintrin.h: No such file or directory
   25 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
[35/75] Building CXX object src/sortmerna/CMakeFiles/smr_objs.dir/Release/cmd.cpp.o
FAILED: src/sortmerna/CMakeFiles/smr_objs.dir/Release/cmd.cpp.o 
/usr/bin/c++ -DCMAKE_INTDIR=\"Release\" -I/tmp/sortmerna/sortmerna/include -I/tmp/sortmerna/sortmerna/3rdparty/cmph -I/tmp/sortmerna/sortmerna/3rdparty/concurrentqueue -I/tmp/sortmerna/sortmerna/3rdparty/alp -isystem /tmp/sortmerna/sortmerna/build/3rdparty/rocksdb/dist/include -isystem /tmp/sortmerna/sortmerna/build/3rdparty/zlib/dist/include -W -Wextra -Wall -Xlinker -v -O3 -DNDEBUG -std=gnu++17 -MD -MT src/sortmerna/CMakeFiles/smr_objs.dir/Release/cmd.cpp.o -MF src/sortmerna/CMakeFiles/smr_objs.dir/Release/cmd.cpp.o.d -o src/sortmerna/CMakeFiles/smr_objs.dir/Release/cmd.cpp.o -c /tmp/sortmerna/sortmerna/src/sortmerna/cmd.cpp
In file included from /tmp/sortmerna/sortmerna/include/indexdb.hpp:40,
                 from /tmp/sortmerna/sortmerna/include/bitvector.hpp:42,
                 from /tmp/sortmerna/sortmerna/include/traverse_bursttrie.hpp:46,
                 from /tmp/sortmerna/sortmerna/include/read.hpp:46,
                 from /tmp/sortmerna/sortmerna/src/sortmerna/cmd.cpp:48:
/tmp/sortmerna/sortmerna/include/ssw.h:25:10: fatal error: emmintrin.h: No such file or directory
   25 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
[42/75] Building CXX object 3rdparty/alp/CMakeFiles/alp.dir/Release/sls_alp_sim.cpp.o
ninja: build stopped: subcommand failed.
None
None
None
```

**Comment by martin-g** [comment]
With https://github.com/sortmerna/sortmerna/pull/417/commits/4ee2e7a9d2c1f1d4f360a2f6ba7a58c9afb5d84f I added usage of [sse2neon](https://github.com/DLTcollab/sse2neon/blob/ae4113db9290fb0838308436faaa26b117e75254/sse2neon.h) for SSE2 operations on ARM64/aarch64.

With that now the build on my Linux ARM64 machine passed:
```
...
===========================================================
cmake --build --preset LIN_release --target package
===========================================================
[0/1] Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Install project: sortmerna [Release]
CPack: Create package
CPackDeb: Using only user-provided dependencies because dpkg-shlibdeps is not found.
-- CPackDeb: Can not find dpkg in your path, default to i386.
-- CPACK_DEBIAN_PACKAGE_DEPENDS not set, the package will have no dependencies.
CPackDeb:Debug: CPACK_TOPLEVEL_DIRECTORY          = '/tmp/sortmerna/sortmerna/dist/_CPack_Packages/Linux/DEB'
CPackDeb:Debug: CPACK_TOPLEVEL_TAG                = 'Linux'
CPackDeb:Debug: CPACK_TEMPORARY_DIRECTORY         = '/tmp/sortmerna/sortmerna/dist/_CPack_Packages/Linux/DEB/sortmerna-4.3.7-Linux'
CPackDeb:Debug: CPACK_OUTPUT_FILE_NAME            = 'sortmerna-4.3.7-Linux.deb'
CPackDeb:Debug: CPACK_OUTPUT_FILE_PATH            = '/tmp/sortmerna/sortmerna/dist/sortmerna-4.3.7-Linux.deb'
CPackDeb:Debug: CPACK_PACKAGE_FILE_NAME           = 'sortmerna-4.3.7-Linux'
CPackDeb:Debug: CPACK_PACKAGE_INSTALL_DIRECTORY   = 'sortmerna 4.3.7'
CPackDeb:Debug: CPACK_TEMPORARY_PACKAGE_FILE_NAME = '/tmp/sortmerna/sortmerna/dist/_CPack_Packages/Linux/DEB/sortmerna-4.3.7-Linux.deb'
CPackDeb:Debug: CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION = ''
CPackDeb:Debug: CPACK_DEBIAN_PACKAGE_SOURCE       = ''
CPack: - package: /tmp/sortmerna/sortmerna/dist/sortmerna-4.3.7-Linux.deb generated.
CPack: Create package using STGZ
CPack: Install projects
CPack: - Install project: sortmerna [Release]
CPack: Create package
CPack: - package: /tmp/sortmerna/sortmerna/dist/sortmerna-4.3.7-Linux.sh generated.
CPack: Create package using TGZ
CPack: Install projects
CPack: - Install project: sortmerna [Release]
CPack: Create package
CPack: - package: /tmp/sortmerna/sortmerna/dist/sortmerna-4.3.7-Linux.tar.gz generated.
[proc_run] Run time: 1.8484461307525635
[proc_run] Running in /tmp/sortmerna/sortmerna:
===========================================================
dist/bin/sortmerna --version
===========================================================
[process:1393] === Options processing starts ... ===
Found value: dist/bin/sortmerna
Found flag: --version
[process:1483] Processing option: version with value: 

SortMeRNA version 4.3.7
Build Date: Mar 21 2024
sortmerna_build_git_sha:@b4f7362f069a7f20f4c5e775be457dc89baf625d@
sortmerna_build_git_date:@2024/03/21 14:46:03@
[proc_run] Run time: 0.004781007766723633
[proc_run] Running in /tmp/sortmerna/sortmerna:
===========================================================
dist/bin/sortmerna -h
===========================================================
[process:1393] === Options processing starts ... ===
Found value: dist/bin/sortmerna
Found flag: -h
[process:1483] Processing option: h with value: 

  Program:      SortMeRNA version 4.3.7
  Copyright:    2016-2020 Clarity Genomics BVBA:
                Turnhoutseweg 30, 2340 Beerse, Belgium
                2014-2016 Knight Lab:
                Department of Pediatrics, UCSD, La Jolla
                2012-2014 Bonsai Bioinformatics Research Group:
                LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
  Disclaimer:   SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
                implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
                See the GNU Lesser General Public License for more details.
  Contributors: Jenya Kopylova   jenya.kopylov@gmail.com
                Laurent Noé      laurent.noe@lifl.fr
                Pierre Pericard  pierre.pericard@lifl.fr
                Daniel McDonald  wasade@gmail.com
                Mikaël Salson    mikael.salson@lifl.fr
                Hélène Touzet    helene.touzet@lifl.fr
                Rob Knight       robknight@ucsd.edu

  Usage:   sortmerna -ref FILE [-ref FILE] -reads FWD_READS [-reads REV_READS] [OPTIONS]:
  -------------------------------------------------------------------------------------------------------------
  | option            type-format           description                                          default      |
  -------------------------------------------------------------------------------------------------------------

    [REQUIRED]
    --ref             PATH        Required  Reference file (FASTA) absolute or relative path.

       Use mutliple times, once per a reference file


    --reads           PATH        Required  Raw reads file (FASTA/FASTQ/FASTA.GZ/FASTQ.GZ).

       Use twice for files with paired reads.
       The file extensions are Not important. The program automatically
       recognizes the file format as flat/compressed, fasta/fastq



    [COMMON]
    --workdir         PATH        Optional  Workspace directory                         USRDIR/sortmerna/run/

       Default structure: WORKDIR/
                              idx/   (References index)
                              kvdb/  (Key-value storage for alignments)
                              out/   (processing output)
                              readb/ (pre-processed reads/index)


    --kvdb            PATH        Optional  Directory for Key-value database            WORKDIR/kvdb

       KVDB is used for storing the alignment results.


    --idx-dir         PATH        Optional  Directory for storing Reference index.      WORKDIR/idx


    --readb           PATH        Optional  Storage for pre-processed reads             WORKDIR/readb/

       Directory storing the split reads, or the random access index of compressed reads


    --fastx           BOOL        Optional  Output aligned reads into FASTA/FASTQ file
    --sam             BOOL        Optional  Output SAM alignment for aligned reads.


    --SQ              BOOL        Optional  Add SQ tags to the SAM file


    --blast           STR         Optional  output alignments in various Blast-like formats

       Sample values: '0'                    - pairwise
                      '1'                    - tabular (Blast - m 8 format)
                      '1 cigar'              - tabular + column for CIGAR
                      '1 cigar qcov'         - tabular + columns for CIGAR and query coverage
                      '1 cigar qcov qstrand' - tabular + columns for CIGAR, query coverage,
                                               and strand


    --aligned         STR/BOOL    Optional  Aligned reads file prefix [dir/][pfx]       WORKDIR/out/aligned

       Directory and file prefix for aligned output i.e. each
       output file goes into the specified directory with the given prefix.
       The appropriate extension: (fasta|fastq|blast|sam|etc) is automatically added.
       Both 'dir' and 'pfx' are optional.
       The 'dir' can be a relative or an absolute path.
       If 'dir' is not specified, the output is created in the WORKDIR/out/
       If 'pfx' is not specified, the prefix 'aligned' is used
       Examples:
       '-aligned $MYDIR/dir_1/dir_2/1' -> $MYDIR/dir_1/dir_2/1.fasta
       '-aligned dir_1/apfx'           -> $PWD/dir_1/apfx.fasta
       '-aligned dir_1/'               -> $PWD/aligned.fasta
       '-aligned apfx'                 -> $PWD/apfx.fasta
       '-aligned  (no argument)'       -> WORKDIR/out/aligned.fasta


    --other           STR/BOOL    Optional  Non-aligned reads file prefix [dir/][pfx]   WORKDIR/out/other

       Directory and file prefix for non-aligned output i.e. each
       output file goes into the specified directory with the given prefix.
       The appropriate extension: (fasta|fastq|blast|sam|etc) is automatically added.
       Must be used with 'fastx'.
       Both 'dir' and 'pfx' are optional.
       The 'dir' can be a relative or an absolute path.
       If 'dir' is not specified, the output is created in the WORKDIR/out/
       If 'pfx' is not specified, the prefix 'other' is used
       Examples:
       '-other $MYDIR/dir_1/dir_2/1' -> $MYDIR/dir_1/dir_2/1.fasta
       '-other dir_1/apfx'           -> $PWD/dir_1/apfx.fasta
       '-other dir_1/'               -> $PWD/dir_1/other.fasta
       '-other apfx'                 -> $PWD/apfx.fasta
       '-other  (no argument)'       -> aligned_out/other.fasta
                                        i.e. the same output directory
                                        as used for aligned output


    --num_alignments  INT         Optional  Positive integer (INT >=0).

       If used with '-no-best' reports first INT alignments per read reaching
       E-value threshold, which allows to lower the CPU time and memory use.
       Otherwise outputs INT best alignments.
       If INT = 0, all alignments are output


    --no-best         BOOL        Optional  Disable best alignments search                          False

       The 'best' alignment is the highest scoring alignment out of All alignments of a read,
       and the read can potentially be aligned (reaching E-value threshold) to multiple reference
       sequences.
       By default the program searches for best alignments i.e. performs an exhaustive search
       over all references. Using '-no-best' will make the program to search just
       the first N alignments, where N is set using '-num_alignments' i.e. 1 by default.


    --min_lis         INT         Optional  Search only alignments that have the LIS                2
                                            of at least N seeds long

       LIS stands for Longest Increasing Subsequence. It is computed using seeds, which
       are k-mers common to the read and the reference sequence. Sorted sequences of such seeds
       are used to filter the candidate references prior performing the Smith-Waterman alignment.


    --print_all_reads BOOL        Optional  Output null alignment strings for non-aligned reads     False
                                            to SAM and/or BLAST tabular files

    --paired          BOOL        Optional  Flags paired reads                                      False

        If a single reads file is provided, use this option to indicate
        the file contains interleaved paired reads when neither
        'paired_in' | 'paired_out' | 'out2' | 'sout' are specified.


    --paired_in       BOOL        Optional  Flags the paired-end reads as Aligned,                  False
                                            when either of them is Aligned.

        With this option both reads are output into Aligned FASTA/Q file
        Must be used with 'fastx'.
        Mutually exclusive with 'paired_out'.


    --paired_out      BOOL        Optional  Flags the paired-end reads as Non-aligned,              False
                                            when either of them is non-aligned.

        With this option both reads are output into Non-Aligned FASTA/Q file
        Must be used with 'fastx'.
        Mutually exclusive with 'paired_in'.


    --out2            BOOL        Optional  Output paired reads into separate files.                False

       Must be used with 'fastx'.
       If a single reads file is provided, this options implies interleaved paired reads
       When used with 'sout', four (4) output files for aligned reads will be generated:
       'aligned-paired-fwd, aligned-paired-rev, aligned-singleton-fwd, aligned-singleton-rev'.
       If 'other' option is also used, eight (8) output files will be generated.


    --sout            BOOL        Optional  Separate paired and singleton aligned reads.            False

       To be used with 'fastx'.
       If a single reads file is provided, this options implies interleaved paired reads
       Cannot be used with 'paired_in' | 'paired_out'


    --zip-out         STR/BOOL    Optional  Controls the output compression                        '-1'

       By default the report files are produced in the same format as the input i.e.
       if the reads files are compressed (gz), the output is also compressed.
       The default behaviour can be overriden by using '-zip-out'.
       The possible values: '1/true/t/yes/y'
                            '0/false/f/no/n'
                            '-1' (the same format as input - default)
       The values are Not case sensitive i.e. 'Yes, YES, yEs, Y, y' are all OK
       Examples:
       '-reads freads.gz -zip-out n' : generate flat output when the input is compressed
       '-reads freads.flat -zip-out' : compress the output when the input files are flat


    --match           INT         Optional  SW score (positive integer) for a match.                2

    --mismatch        INT         Optional  SW penalty (negative integer) for a mismatch.          -3

    --gap_open        INT         Optional  SW penalty (positive integer) for introducing a gap.    5

    --gap_ext         INT         Optional  SW penalty (positive integer) for extending a gap.      2

    -e                DOUBLE      Optional  E-value threshold.                                      1

       Defines the 'statistical significance' of a local alignment.
       Exponentially correllates with the Minimal Alignment score.
       Higher E-values (100, 1000, ...) cause More reads to Pass the alignment threshold


    -F                BOOL        Optional  Search only the forward strand.                         False

    -N                BOOL        Optional  SW penalty for ambiguous letters (N's) scored
                                            as --mismatch

    -R                BOOL        Optional  Search only the reverse-complementary strand.           False


    [OTU_PICKING]
    --id              INT         Optional  %%id similarity threshold (the alignment                0.97
                                            must still pass the E-value threshold).

    --coverage        INT         Optional  %%query coverage threshold (the alignment must          0.97
                                            still pass the E-value threshold)

    --de_novo_otu     BOOL        Optional  Output FASTA file with 'de novo' reads                  False

       Read is 'de novo' if its alignment score passes E-value threshold, but both the identity
       '-id', and the '-coverage' are below their corresponding thresholds
       i.e. ID < %%id and COV < %%cov


    --otu_map         BOOL        Optional  Output OTU map (input to QIIME's make_otu_table.py).    False
                                            Cannot be used with 'no-best because
                                            the grouping is done around the best alignment'


    [ADVANCED]
    --passes          INT,INT,INT Optional  Three intervals at which to place the seed on           L,L/2,3
                                             the read (L is the seed length)

    --edges           INT         Optional  Number (or percent if INT followed by %% sign) of       4
                                            nucleotides to add to each edge of the read
                                            prior to SW local alignment

    --num_seeds       BOOL        Optional  Number of seeds matched before searching                2
                                            for candidate LIS

    --full_search     INT         Optional  Search for all 0-error and 1-error seed                 False
                                            matches in the index rather than stopping
                                            after finding a 0-error match (<1%% gain in
                                            sensitivity with up four-fold decrease in speed)

    --pid             BOOL        Optional  Add pid to output file names.                           False

    -a                INT         Optional  DEPRECATED in favour of '-threads'. Number of           numCores
                                            processing threads to use.
                                            Automatically redirects to '-threads'

    --threads         INT         Optional  Number of Processing threads to use                     2


    [INDEXING]
    --index           INT         Optional  Build reference database index                          2

       By default when this option is not used, the program checks the reference index and
       builds it if not already existing.
       This can be changed by using '-index' as follows:
       '-index 0' - skip indexing. If the index does not exist, the program will terminate
                                and warn to build the index prior performing the alignment
       '-index 1' - only perform the indexing and terminate
       '-index 2' - the default behaviour, the same as when not using this option at all


    -L                DOUBLE      Optional  Indexing: seed length.                                  18

    -m                DOUBLE      Optional  Indexing: the amount of memory (in Mbytes) for          3072
                                            building the index.

    -v                BOOL        Optional  Produce verbose output when building the index          True

    --interval        INT         Optional  Indexing: Positive integer: index every Nth L-mer in    1
                                            the reference database e.g. '-interval 2'.

    --max_pos         INT         Optional  Indexing: maximum (integer) number of positions to      1000
                                            store for each unique L-mer.
                                            If 0 - all positions are stored.


    [HELP]
    -h                BOOL        Optional  Print help information

    --version         BOOL        Optional  Print SortMeRNA version number


    [DEVELOPER]
    --dbg_put_db      BOOL        Optional  
    --cmd             BOOL        Optional  Launch an interactive session (command prompt)          False

    --task            INT         Optional  Processing Task                                         4

       Possible values: 0 - align. Only perform alignment
                        1 - post-processing (log writing)
                        2 - generate reports
                        3 - align and post-process
                        4 - all


    --dbg-level       INT         Optional  Debug level                                             0

      Controls verbosity of the execution trace. Default value of 0 corresponds to
      the least verbose output.
      The highest value currently is 2.
```

```
$ file dist/bin/sortmerna                                                                                                                                                                                dist/bin/sortmerna: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=f05b0fac5d35a04cfb6e5dbbca37a1720a2e196f, for GNU/Linux 3.7.0, not stripped
```

**Comment by martin-g** [comment]
The Linux ARM64 build on my fork passed - https://github.com/martin-g/sortmerna/actions/runs/8387357075/job/22969405241
But the windows and osx builds failed due to unrelated reasons.

**Comment by biocodz** [comment]
The windows build is broken. It doesn't like the new includes in ssw.c
```
...
2024-04-04T21:29:00.7990776Z C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1438~1.331\bin\HostX64\x64\cl.exe  /nologo -DCMAKE_INTDIR=\"Release\" -ID:\a\sortmerna\sortmerna\include -ID:\a\sortmerna\sortmerna\src\winapi\include -ID:\a\sortmerna\sortmerna\3rdparty\cmph -ID:\a\sortmerna\sortmerna\3rdparty\dirent\include -ID:\a\sortmerna\sortmerna\3rdparty\concurrentqueue -ID:\a\sortmerna\sortmerna\3rdparty\alp -external:ID:\a\sortmerna\sortmerna\build\3rdparty\rocksdb\dist\include -external:ID:\a\sortmerna\sortmerna\build\3rdparty\zlib\dist\include -external:W0 /DWIN32 /D_WINDOWS /O2 /Ob2 /DNDEBUG -MD /showIncludes /Fosrc\sortmerna\CMakeFiles\smr_objs.dir\Release\ssw.c.obj /Fdsrc\sortmerna\CMakeFiles\smr_objs.dir\Release\ /FS -c D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c
2024-04-04T21:29:00.8994639Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(87): error C2061: syntax error: identifier '__m128i'
2024-04-04T21:29:00.8997224Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(88): error C2143: syntax error: missing '{' before '*'
2024-04-04T21:29:00.8999150Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(94): error C2059: syntax error: '}'
2024-04-04T21:29:00.9000980Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(110): error C2143: syntax error: missing '{' before '*'
2024-04-04T21:29:00.9002834Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(120): error C2065: '__m128i': undeclared identifier
2024-04-04T21:29:00.9055216Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(120): error C2065: 'vProfile': undeclared identifier
2024-04-04T21:29:00.9087352Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(120): error C2065: '__m128i': undeclared identifier
2024-04-04T21:29:00.9089129Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(120): error C2059: syntax error: ')'
2024-04-04T21:29:00.9090928Z D:\a\sortmerna\sortmerna\src\sortmerna\ssw.c(121): error C2065: 'vProfile': undeclared identifier
...
```

**Comment by biocodz** [comment]
The update still didn't go through. Seems MS having issues with their network for the past couple of days. Eventually it'll get fixed

**Comment by martin-g** [comment]
The commit appeared in my fork - https://github.com/martin-g/sortmerna/commit/0004159f176065f29eed3bcd0cb14956bbc95bc8
But not yet in the PR...

**Review by biocodz — APPROVED** [review]
Looks good and all checks have passed. Very valuable contribution

**Comment by martin-g** [comment]
Awesome!
May I ask for a new release please !

**Comment by biocodz** [comment]
I was waiting for Conda to merge my [PR for sortmerna](https://github.com/conda-forge/staged-recipes/pull/25438) before making the release. But it's hanging there already for a couple of months. I guess it's time to proceed with the release. Let me run some tests, and then to finalize this

**Pull request merged**
